
version: "3.8"

services:

  gitops-committer:
    image: supercash/resources/gitops-committer
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ./gitops:/metadata
    environment:
      - GITOPS_TRIGGER_REPO=git@github.com:marcellodesales/iot-observability.git
      - GITOPS_TRIGGER_PIPELINE_URL=https://gitlab.com/supercash/services/reverse-proxy-resource/-/pipelines/256841576
      - GITOPS_TRIGGER_BRANCH=main
      - GITOPS_TRIGGER_SHA=101020304
      - GITOPS_EXECUTOR_SCRIPT=/gitops/executor.sh
      - GITOPS_EXECUTOR_COMMIT_MSG="Supercash GitOps"
      - GITOPS_EXECUTOR_COMMIT_AUTHOR_NAME="Marcello de Sales"
      - GITOPS_EXECUTOR_COMMIT_AUTHOR_EMAIL=marcello.desales@gmail.com
      - GITOPS_METADATA_VALUES_FILE=/metadata/supercash-deployer.yaml
